# HELLBLOCK CONFIGURATION #

# Developer: @Swiftlicious
config-version: '1'

# Debug
debug: false

# BStats
metrics: true

# Check updates
update-checker: true

general:
  world: hellworld
  spawnSize: 50
  netherCMD: '/spawn'
hellblock:
  can-transfer-islands: true
  party-size: 4
  schematic: yourschematicname
  useClassicShape: false
  height: 150
  distance: 110
  worldguardProtect: true
  protectionRange: 105
  starter-chest: 
    - air 
    - air 
    - air 
    - brown_mushroom 
    - oak_sign 
    - red_mushroom 
    - air 
    - air 
    - air 
    - oak_sapling 
    - air 
    - air 
    - lava_bucket 
    - bucket 
    - lava_bucket 
    - air 
    - air 
    - air 
    - grass_block 
    - air 
    - air 
    - bone 
    - nether_wart 
    - bone 
    - air 
    - air 
    - air
  allowPvP: deny
 
infinite-lava-options:
  # At which height (block - not line of sight!) is the lava unlimited
  height: 60
  sources:
    # Different sources -> See the schematics below
    three: true
    two: true
    other: false
    big: false
    lava-fall: true
    plus: true
    T: true
    ring: true
  
lava-rain-options:
  # How far from the player should the lava particles fall (setting this value too high may cause lag !)
  radius: 16
  # Chance to make fire appear on the ground when the lava is falling
  fireChance: 1
  # Every how many ticks should the task repeat (20 ticks is 1 second)
  taskDelay: 3

generator-options:
  playerSearchRadius: 4.0
  automation:
    pistons: false
  generationModes:
    '0':
      blocks:
        - LAVA
        - LAVA
      displayName: Netherrack generator
      fallback: NETHERRACK
      particleEffect: LARGE_SMOKE
      generationSound: ENTITY_EXPERIENCE_ORB_PICKUP
      canGenerateWhileLavaRaining: true

# mechanism settings
mechanism:
  # Specifies the conditions required for the plugin mechanism to work.
  # Here, the type is !world, which implies the plugin won't work in
  # the world named 'blacklist_world'.
  mechanism-requirements:
    world_requirement:
      type: '!world'
      value:
        - blacklist_world
      # Configures global effects. This is useful if you want to give all the players certain effects based on certain conditions
      global-effects:
        effect_1:
          type: conditional
          effects:
            effect_1:
              type: wait-time-multiplier
              value: 0.85

      # Configures global events for hook/bait/rod/loot
      # which would help you reduce duplicated lines
      global-events:
        hook: {}
        bait: {}
        loot:
          new_size_record:
            conditional_size_record_action:
              type: conditional
              value:
                conditions:
                  has-stats: true
                actions:
                  actionbar_action:
                    type: actionbar
                    value: '<#FFD700>[New Record]</#FFD700> <#FFFFF0>You caught a(n) {nick} which is <#FFA500>{size}cm</#FFA500> long!</#FFFFF0>'
                  sound_action:
                    type: sound
                    value:
                      key: "minecraft:block.note_block.cow_bell"
                      source: 'player'
                      volume: 1
                      pitch: 1
                  delayed_sound:
                    type: delay
                    value:
                      delay: 2
                      actions:
                        sound_action:
                          type: sound
                          value:
                            key: "minecraft:block.note_block.bell"
                            source: 'player'
                            volume: 1
                            pitch: 1
          success:
            conditional_size_info_action:
              type: conditional
              value:
                conditions:
                  has-size: true
                  has-stats: true
                actions:
                  actionbar_action:
                    type: actionbar
                    value: '<gray>You caught a(n) {nick} which is <#F5F5F5>{size}cm</#F5F5F5> long!</gray> <#C0C0C0>(Best record: {record}cm)</#C0C0C0>'
            title_action:
              type: random-title
              value:
                titles:
                  - '<green>GG!</green>'
                  - '<green>Good Job!</green>'
                subtitles:
                  - 'You caught a(n) {nick}'
                  - 'Whoa! Nice catch!'
                  - 'Oh {nick} here we go!'
                  - 'Let''s see what it is!'
                fade-in: 20
                stay: 30
                fade-out: 10
              chance: 1.0
          failure:
            title_action:
              type: random-title
              value:
                titles:
                  - '<red>Be concentrated!</red>'
                  - '<red>What a pity!</red>'
                  - '<red>Try next time!</red>'
                  - '<red>Bad luck</red>'
                subtitles:
                  - 'The fish escaped...'
                fade-in: 20
                stay: 30
                fade-out: 10
              chance: 1.0
        rod:
          land:
            priority_action:
              type: priority
              value:
                priority_1:
                  conditions:
                    lava-fishing: true
                  actions:
                    fake_item_action:
                      type: fake-item
                      value:
                        duration: 35
                        position: other
                        item: util:lava_effect
                priority_2:
                  conditions:
                    lava-fishing: false
                  actions:
                    fake_item_action:
                      type: fake-item
                      value:
                        duration: 35
                        position: other
                        item: util:water_effect

      # Global properties which would help you reduce duplicated lines
      global-loot-property:
        show-in-fishfinder: true

      # Fishing wait time
      # This section would take effect if you set "override-vanilla" to true
      # That also means vanilla mechanics for example lure enchantment
      # would no longer take effect, so you have to configurate its effect
      # in enchantment effects.
      fishing-wait-time:
        # override vanilla mechanic
        override-vanilla: false

      # Lava fishing settings
      # To modify vanilla fishing time, you should edit paper-world-defaults.yml where there's a section called fishing-time-range
      lava-fishing:
        # ticks
        min-wait-time: 100
        max-wait-time: 600

      # Size settings
      size:
        # Some effects would increase/decrease size so the option decides whether they could ignore the limit
        restricted-size-range: true

      # If a player could get multiple loots from fishing, should the loots spawn at the same time or have delays for each (tick)
      multiple-loot-spawn-delay: 4

# Other settings
other-settings:
 
    # It's recommended to use MiniMessage format. If you insist on using legacy color code "&", enable the support below.
    # Disable this would improve performance
    legacy-color-code-support: true

    # Thread pool settings
    thread-pool-settings:
      # The size of the core Thread pool, that is, the size of the Thread pool when there is no task to execute
      # Increase the size of corePoolSize when you are running a large server with many players fishing at the same time
      corePoolSize: 10
      # The maximum number of threads allowed to be created in the Thread pool. The current number of threads in the Thread pool will not exceed this value
      maximumPoolSize: 10
      # If a thread is idle for more than this attribute value, it will exit due to timeout
      keepAliveTime: 30

    # Event priority: MONITOR HIGHEST HIGH NORMAL LOW LOWEST
    event-priority: NORMAL

    # Save the data from cache to file periodically to minimize the data loss if server crashes
    # -1 to disable
    data-saving-interval: 600

    # Log the consumption of time on data saving
    log-data-saving: true

    # Lock player's data if a player is playing on a server that connected to database
    # If you can ensure low database link latency and fast processing, you can consider disabling this option to improve performance
    lock-data: true

    # Requires PlaceholderAPI to work
    placeholder-register:
      '{record}': '%fishingstats_size-record_{loot}%'
      # Requires server expansion
      '{date}': '%server_time_yyyy-MM-dd-HH:mm:ss%'
      # Requires player expansion
      '{yaw}': '%player_yaw%'

    # LavaFishing supports using items/blocks from other plugins
    # If items share the same id, they would inherit the effects
    # Check the wiki for examples
    item-detection-order:
      - LavaFishing
      - vanilla
    block-detection-order:
      - vanilla

    # Custom durability format
    custom-durability-format:
      - ''
      - '<gray>Durability</gray><white>: {dur} <gray>/</gray> {max}</white>'

    # Offset characters' unicodes
    # Never edit this unless you know what you are doing
    offset-characters:
      font: hellblock:offset_chars
      '1': 
      '2': 
      '4': 
      '8': 
      '16': 
      '32': 
      '64': 
      '128': 
      '-1': 
      '-2': 
      '-4': 
      '-8': 
      '-16': 
      '-32': 
      '-64': 
      '-128': 