[versions]
pluginVersion = "1.0-ALPHA"
folia = "1.21.11-R0.1-SNAPSHOT"
aswm = "4.2.0-SNAPSHOT"

# Adventure
adventureapi = "4.26.1"
adventureplatformapi = "4.4.1"
adventureexaminationapi = "1.3.0"
adventureoption = "1.1.0"

# Cloud
cloudcore = "2.0.0"
cloudservices = "2.0.0"
cloudbrigadier = "2.0.0-beta.14"
cloudbukkit = "2.0.0-beta.14"
cloudpaper = "2.0.0-beta.14"
cloudminecraftextras = "2.0.0-beta.14"

# Logging
log4j = "3.0.0-beta3"
slf4j = "2.1.0-alpha1"

# Serialization
gson = "2.13.2"
boostedyaml = "1.3.7"

# Auth & NBT
authlib = "3.11.50"
jackson = "2.18.0"
bytebuddy = "1.18.3"
spotbugs = "4.9.8"

# Math, Compression, Caching
exp4j = "0.4.8"
lz4 = "1.10.2"
zstd = "1.5.7-6"
caffeine = "3.2.3"

# RTag
rtag = "1.5.14"

# Placeholder API / Vault
placeholderapi = "2.11.7"
vault = "1.7"

# MythicMobs / ShopGUI+ / Jobs
mythicmobs = "5.11.1"
shopgui = "3.2.0"
jobs = "v5.2.6.3"
playerpoints = "3.3.3"
simplepets = "5.0-BUILD-287"
chestshop = "3.12.2"
tradeshop = "2.6.0-DEV-2022-11-28T01.29.14"
quickshop = "5.1.2.5-SNAPSHOT"
multiversecore = "5.4.0-SNAPSHOT"
protocollib = "5.4.0"

# Needed for QuickShop
openinv = "5.1.6"
jsonconfiguration = "1.1"
jsonsmart = "2.6.0"

# Needed for JobsReborn
stackermob = "5.10.3"
mcmmo = "2.2.031"
wildstacker = "3.8.1"

# Databases
mysql = "9.5.0"
mariadb = "3.5.7"
postgresql = "42.7.8"
sqlite = "3.51.1.0"
h2 = "2.4.240"
mongodb = "5.7.0-alpha0"

# Connection Pools
hikari = "7.0.2"
commonspool = "2.13.0"
jedis = "7.2.0"

# WorldEdit / WorldGuard
worldedit = "7.4.0-SNAPSHOT"
worldguard = "7.1.0-SNAPSHOT"

# Geyser
geyser = "2.9.0-SNAPSHOT"
floodgate = "2.2.5-SNAPSHOT"

# Bytecode 
asm = "9.9.1" 
asmcommons = "9.9.1" 
jarrelocator = "1.7"

# Misc
immutables = "2.12.0"
geantyref = "2.0.1"
paperlib = "1.0.8"

[libraries]
# Kyori Adventure
adventureapi = { module = "net.kyori:adventure-api", version.ref = "adventureapi" }
adventureexaminationapi = { module = "net.kyori:examination-api", version.ref = "adventureexaminationapi" }
adventureexaminationstring = { module = "net.kyori:examination-string", version.ref = "adventureexaminationapi" }
adventureoption = { module = "net.kyori:option", version.ref = "adventureoption" }
adventureminimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventureapi" }
adventureplatformbukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventureplatformapi" }
adventureplatformfacet = { module = "net.kyori:adventure-platform-facet", version.ref = "adventureplatformapi" }
adventureplatformapi = { module = "net.kyori:adventure-platform-api", version.ref = "adventureplatformapi" }
adventurejsonlegacy = { module = "net.kyori:adventure-text-serializer-json-legacy-impl", version.ref = "adventureapi" }
adventurelegacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventureapi" }
adventuregson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventureapi" }
adventurejson = { module = "net.kyori:adventure-text-serializer-json", version.ref = "adventureapi" }
adventureplain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventureapi" }
adventurenbt = { module = "net.kyori:adventure-nbt", version.ref = "adventureapi" }
adventurekey = { module = "net.kyori:adventure-key", version.ref = "adventureapi" }

# RTag
rtagcore = { module = "com.saicone.rtag:rtag", version.ref = "rtag" }
rtagitem = { module = "com.saicone.rtag:rtag-item", version.ref = "rtag" }
rtagentity = { module = "com.saicone.rtag:rtag-entity", version.ref = "rtag" }

# Cloud
cloudcore = { module = "org.incendo:cloud-core", version.ref = "cloudcore" }
cloudservices = { module = "org.incendo:cloud-services", version.ref = "cloudservices" }
cloudbrigadier = { module = "org.incendo:cloud-brigadier", version.ref = "cloudbrigadier" }
cloudbukkit = { module = "org.incendo:cloud-bukkit", version.ref = "cloudbukkit" }
cloudpaper = { module = "org.incendo:cloud-paper", version.ref = "cloudpaper" }
cloudminecraftextras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloudminecraftextras" }

# Paper
folia = { module = "dev.folia:folia-api", version.ref = "folia" }
spigot = { module = "org.spigotmc:spigot-api", version.ref = "folia" }
paper = { module = "io.papermc.paper:paper-api", version.ref = "folia" }
paperlib = { module = "io.papermc:paperlib", version.ref = "paperlib" }
aswm = { module = "com.infernalsuite.asp:api", version.ref = "aswm" }

# PlaceholderAPI, Vault, Jobs, MythicMobs
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
vault = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
playerpoints = { module = "org.black_ixx:playerpoints", version.ref = "playerpoints" }
jobs = { module = "com.github.Zrips:Jobs", version.ref = "jobs" }
wildstacker = { module = "com.bgsoftware:WildStackerAPI", version.ref = "wildstacker" }
stackermob = { module = "uk.antiperson.stackmob:StackMob", version.ref = "stackermob" }
mcmmo = { module = "com.gmail.nossr50.mcMMO:mcMMO", version.ref = "mcmmo" }
mythicmobs = { module = "io.lumine:Mythic-Dist", version.ref = "mythicmobs" }
simplepets = { module = "simplepets.brainsynder:API", version.ref = "simplepets" }
shopgui = { module = "com.github.brcdev-minecraft:shopgui-api", version.ref = "shopgui" }
chestshop = { module = "com.acrobot.chestshop:chestshop", version.ref = "chestshop" }
tradeshop = { module = "com.github.TradeShop:TradeShop", version.ref = "tradeshop" }
quickshop = { module = "org.maxgamer:QuickShop", version.ref = "quickshop" }
openinv = { module = "com.github.jikoo.OpenInv:openinvapi", version.ref = "openinv" }
jsonconfiguration = { module = "com.dumptruckman.minecraft:JsonConfiguration", version.ref = "jsonconfiguration" }
jsonsmart = { module = "net.minidev:json-smart", version.ref = "jsonsmart" }
multiversecore = { module = "org.mvplugins.multiverse.core:multiverse-core", version.ref = "multiversecore" }
protocollib = { module = "net.dmulloy2:ProtocolLib", version.ref = "protocollib" }

# Logging
log4j = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# Serialization / YAML / Auth
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
boostedyaml = { module = "dev.dejvokep:boosted-yaml", version.ref = "boostedyaml" }
authlib = { module = "com.mojang:authlib", version.ref = "authlib" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jacksonannotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
bytebuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }
spotbugs = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }

# WorldEdit & WorldGuard
worldeditcore = { module = "com.sk89q.worldedit:worldedit-core", version.ref = "worldedit" }
worldeditbukkit = { module = "com.sk89q.worldedit:worldedit-bukkit", version.ref = "worldedit" }
worldeditlibscore = { module = "com.sk89q.worldedit.worldedit-libs:core", version.ref = "worldedit" }
worldeditlibsbukkit = { module = "com.sk89q.worldedit.worldedit-libs:bukkit", version.ref = "worldedit" }
worldguardcore = { module = "com.sk89q.worldguard:worldguard-core", version.ref = "worldguard" }
worldguardbukkit = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
worldguardlibscore = { module = "com.sk89q.worldguard.worldguard-libs:core", version.ref = "worldguard" }

# Drivers
mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }

# Mongo / Redis
mongodb = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb" }
jedis = { module = "redis.clients:jedis", version.ref = "jedis" }

# Connection Pools
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
commonspool = { module = "org.apache.commons:commons-pool2", version.ref = "commonspool" }

# Utility Libraries
immutables = { module = "org.immutables:value", version.ref = "immutables" }
geantyref = { module = "org.checkerframework:geantyref", version.ref = "geantyref" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
exp4j = { module = "net.objecthunter:exp4j", version.ref = "exp4j" }
lz4 = { module = "at.yawk.lz4:lz4-java", version.ref = "lz4" }

# Geyser & Floodgate
geyser = { module = "org.geysermc.geyser:api", version.ref = "geyser" }
floodgate = { module = "org.geysermc.floodgate:api", version.ref = "floodgate" }